#!/bin/bash
if [ ! -f /tmp/BH-Athan/BH-Icon.png ]; then
if [ ! -d /tmp/BH-Athan ]; then
cd /tmp/
mkdir BH-Athan
fi
cd /tmp/BH-Athan
wget https://lh3.ggpht.com/0FgM91krveBVeA_Y8NihhHNtJMQavdiHUu1a86LEFWqywOGtre-EW7XAmYnZtvFUsXY
mv 0FgM91krveBVeA_Y8NihhHNtJMQavdiHUu1a86LEFWqywOGtre-EW7XAmYnZtvFUsXY BH-Icon.png
fi
if [ ! -f /bin/$($0 | awk -F"./" '{print $2}') ]; then
cp $(pwd)/$($0 | awk -F"./" '{print $2}') /bin/BH-Athan
chmod +x /bin/BH-Athan
fi
if [ ! -f /home/$(uname -a | awk '{print $2}')/.config/autostart/Athan.desktop ]; then
cd /home/$(uname -a | awk '{print $2}')/.config/autostart/
echo '[Desktop Entry]
Encoding=UTF-8
Version=0.9.4
Type=Application
Name=Athan
Comment=Coded By Black Hawk
Exec=/bin/BH-Athan
OnlyShowIn=XFCE;
StartupNotify=false
Terminal=false
Hidden=false' > Athan.desktop
fi
if [ ! -d /tmp/BH-Athan ]; then
mkdir /tmp/BH-Athan
cd /tmp/BH-Athan
if [ ! -f adhan11.wma ]; then
wget http://iraq.iraq.ir/islam/adhan/adhan11.wma
clear
fi
if [ ! -f /tmp/BH-Athan/duhur.mp3 ]; then
cd /tmp/BH-Athan
wget https://archive.org/download/fajer_201511/duhur.mp3
clear
fi
if [ ! -f /tmp/BH-Athan/fajer.mp3 ]; then
cd /tmp/BH-Athan
wget https://archive.org/download/fajer_201511/fajer.mp3
clear
fi
if [ ! -f /tmp/BH-Athan/maghrib.mp3 ]; then
cd /tmp/BH-Athan
wget https://archive.org/download/fajer_201511/maghrib.mp3
clear
fi
while [ 1 ]; do
time=$(date | awk '{print $4}')
con=$(curl -s http://cmyip.com/ | grep "Region:" | awk '{print $3}')
case $con in
Baghdad)
if [ $time == "05:00:00" ]; then
cd /tmp/BH-Athan
notify-send "BH-Athan" "حان الان موعد اذان الفجر حسب التوقيت المحلي لمدينة بغداد وضواحيها." -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
mplayer fajer.mp3
mplayer adhan11.wma
fi
if [ $time == "11:47:00" ]; then
notify-send "BH-Athan" "حان الان موعد اذان الضهر حسب التوقيت المحلي لمدينة بغداد وضواحيها" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
cd /tmp/BH-Athan
mplayer duhur.mp3
mplayer adhan11.wma
fi
if [ $time == "17:21:00" ]; then
notify-send "BH-Athan" "حان الان موعد اذان المغرب حسب التوقيت المحلي لمدينة بغداد وضواحيها" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
cd /tmp/BH-Athan
mplayer maghrib.mp3
mplayer adhan11.wma
fi
;;
Diyala)
if [ $time == "05:00:00" ]; then
cd /tmp/BH-Athan
notify-send "BH-Athan" "حان الان موعد اذان الفجر حسب التوقيت المحلي لمدينة ديالى وضواحيها" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
mplayer fajer.mp3
mplayer adhan11.wma
fi
if [ $time == "11:47:00" ]; then
notify-send "BH-Athan" "حان الان موعد اذان الضهر حسب التوقيت المحلي لمدينة ديالى وضواحيها" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
cd /tmp/BH-Athan
mplayer duhur.mp3
mplayer adhan11.wma
fi
if [ $time == "17:21:00" ]; then
notify-send "BH-Athan" "حان الان موعد اذان المغرب حسب التوقيت المحلي لمدينة ديالى وضواحيها" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
cd /tmp/BH-Athan
mplayer maghrib.mp3
mplayer adhan11.wma
fi
;;
Erbil)
if [ $time == "05:00:00" ]; then
cd /tmp/BH-Athan
notify-send "BH-Athan" "حان الان موعد اذان الفجر حسب التوقيت المحلي لمدينة اربيل وضواحيها" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
mplayer fajer.mp3
mplayer adhan11.wma
fi
if [ $time == "11:47:00" ]; then
notify-send "BH-Athan" "حان الان موعد اذان الضهر حسب التوقيت المحلي لمدينة اربيل وضواحيها" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
cd /tmp/BH-Athan
mplayer duhur.mp3
mplayer adhan11.wma
fi
if [ $time == "17:21:00" ]; then
notify-send "BH-Athan" "حان الان موعد اذان المغرب حسب التوقيت المحلي لمدينة اربيل وضواحيها" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
cd /tmp/BH-Athan
mplayer maghrib.mp3
mplayer adhan11.wma
fi
;;
Basra)
if [ $time == "05:00:00" ]; then
cd /tmp/BH-Athan
notify-send "BH-Athan" "حان الان موعد اذان الفجر حسب التوقيت المحلي لمدينة البصرة وضواحيها" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
mplayer fajer.mp3
mplayer adhan11.wma
fi
if [ $time == "11:47:00" ]; then
notify-send "BH-Athan" "حان الان موعد اذان الضهر حسب التوقيت المحلي لمدينة البصرة وضواحيها" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
cd /tmp/BH-Athan
mplayer duhur.mp3
mplayer adhan11.wma
fi
if [ $time == "17:21:00" ]; then
notify-send "BH-Athan" "حان الان موعد اذان المغرب حسب التوقيت المحلي لمدينة البصرة وضواحيها" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
cd /tmp/BH-Athan
mplayer maghrib.mp3
mplayer adhan11.wma
fi
;;
"Al Anbar")
if [ $time == "05:00:00" ]; then
cd /tmp/BH-Athan
notify-send "BH-Athan" "حان الان موعد اذان الفجر حسب التوقيت المحلي لمدينة الانبار وضواحيها" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
mplayer fajer.mp3
mplayer adhan11.wma
fi
if [ $time == "11:47:00" ]; then
notify-send "BH-Athan" "حان الان موعد اذان الضهر حسب التوقيت المحلي لمدينة الانبار وضواحيها" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
cd /tmp/BH-Athan
mplayer duhur.mp3
mplayer adhan11.wma
fi
if [ $time == "17:21:00" ]; then
notify-send "BH-Athan" "حان الان موعد اذان المغرب حسب التوقيت المحلي لمدينة الانبار وضواحيها" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
cd /tmp/BH-Athan
mplayer maghrib.mp3
mplayer adhan11.wma
fi
;;
Karbala)
if [ $time == "05:00:00" ]; then
cd /tmp/BH-Athan
notify-send "BH-Athan" "حان الان موعد اذان الفجر حسب التوقيت المحلي لمدينة كربلاء المقدسة وضواحيها" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
mplayer fajer.mp3
mplayer adhan11.wma
fi
if [ $time == "11:47:00" ]; then
notify-send "BH-Athan" "حان الان موعد اذان الضهر حسب التوقيت المحلي لمدينة كربلاء المقدسة وضواحيها" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
cd /tmp/BH-Athan
mplayer duhur.mp3
mplayer adhan11.wma
fi
if [ $time == "17:21:00" ]; then
notify-send "BH-Athan" "حان الان موعد اذان المغرب حسب التوقيت المحلي لمدينة كربلاء المقدسة وضواحيها" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
cd /tmp/BH-Athan
mplayer maghrib.mp3
mplayer adhan11.wma
fi
;;
Kirkuk)
if [ $time == "05:00:00" ]; then
cd /tmp/BH-Athan
notify-send "BH-Athan" "حان الان موعد اذان الفجر حسب التوقيت المحلي لمدينة كركوك وضواحيها" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
mplayer fajer.mp3
mplayer adhan11.wma
fi
if [ $time == "11:47:00" ]; then
notify-send "BH-Athan" "حان الان موعد اذان الضهر حسب التوقيت المحلي لمدينة كركوك وضواحيها" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
cd /tmp/BH-Athan
mplayer duhur.mp3
mplayer adhan11.wma
fi
if [ $time == "17:21:00" ]; then
notify-send "BH-Athan" "حان الان موعد اذان المغرب حسب التوقيت المحلي لمدينة كركوك وضواحيها" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
cd /tmp/BH-Athan
mplayer maghrib.mp3
mplayer adhan11.wma
fi
;;
Ninawa)
if [ $time == "05:00:00" ]; then
cd /tmp/BH-Athan
notify-send "BH-Athan" "حان الان موعد اذان الفجر حسب التوقيت المحلي لمدينة نينوى وضواحيها" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
mplayer fajer.mp3
mplayer adhan11.wma
fi
if [ $time == "11:47:00" ]; then
notify-send "BH-Athan" "حان الان موعد اذان الضهر حسب التوقيت المحلي لمدينة نينوى وضواحيها" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
cd /tmp/BH-Athan
mplayer duhur.mp3
mplayer adhan11.wma
fi
if [ $time == "17:21:00" ]; then
notify-send "BH-Athan" "حان الان موعد اذان المغرب حسب التوقيت المحلي لمدينة نينوى وضواحيها" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
cd /tmp/BH-Athan
mplayer maghrib.mp3
mplayer adhan11.wma
fi
;;
Wasit)
if [ $time == "05:00:00" ]; then
cd /tmp/BH-Athan
notify-send "BH-Athan" "حان الان موعد اذان الفجر حسب التوقيت المحلي لمدينة واسط وضواحيها" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
mplayer fajer.mp3
mplayer adhan11.wma
fi
if [ $time == "11:47:00" ]; then
notify-send "BH-Athan" "حان الان موعد اذان الضهر حسب التوقيت المحلي لمدينة واسط وضواحيها" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
cd /tmp/BH-Athan
mplayer duhur.mp3
mplayer adhan11.wma
fi
if [ $time == "17:21:00" ]; then
notify-send "BH-Athan" "حان الان موعد اذان المغرب حسب التوقيت المحلي لمدينة واسط وضواحيها" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
cd /tmp/BH-Athan
mplayer maghrib.mp3
mplayer adhan11.wma
fi
;;
Najaf)
if [ $time == "05:00:00" ]; then
cd /tmp/BH-Athan
notify-send "BH-Athan" "حان الان موعد اذان الفجر حسب التوقيت المحلي لمدينة النجف الاشرف وضواحيها" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
mplayer fajer.mp3
mplayer adhan11.wma
fi
if [ $time == "11:47:00" ]; then
notify-send "BH-Athan" "حان الان موعد اذان الضهر حسب التوقيت المحلي لمدينة النجف الاشرف وضواحيها" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
cd /tmp/BH-Athan
mplayer duhur.mp3
mplayer adhan11.wma
fi
if [ $time == "17:21:00" ]; then
notify-send "BH-Athan" "حان الان موعد اذان المغرب حسب التوقيت المحلي لمدينة النجف الاشرف وضواحيها" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
cd /tmp/BH-Athan
mplayer maghrib.mp3
mplayer adhan11.wma
fi
;;
"Dhi Qar")
if [ $time == "05:00:00" ]; then
cd /tmp/BH-Athan
notify-send "BH-Athan" "حان الان موعد اذان الفجر حسب التوقيت المحلي لمدينة ذي قار وضواحيها" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
mplayer fajer.mp3
mplayer adhan11.wma
fi
if [ $time == "11:47:00" ]; then
notify-send "BH-Athan" "حان الان موعد اذان الضهر حسب التوقيت المحلي لمدينة ذي قار وضواحيها" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
cd /tmp/BH-Athan
mplayer duhur.mp3
mplayer adhan11.wma
fi
if [ $time == "17:21:00" ]; then
notify-send "BH-Athan" "حان الان موعد اذان المغرب حسب التوقيت المحلي لمدينة ذي قار وضواحيها" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
cd /tmp/BH-Athan
mplayer maghrib.mp3
mplayer adhan11.wma
fi
;;
"Al Muthana")
if [ $time == "05:00:00" ]; then
cd /tmp/BH-Athan
notify-send "BH-Athan" "حان الان موعد اذان الفجر حسب التوقيت المحلي لمدينة المثنى وضواحيها" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
mplayer fajer.mp3
mplayer adhan11.wma
fi
if [ $time == "11:47:00" ]; then
notify-send "BH-Athan" "حان الان موعد اذان الضهر حسب التوقيت المحلي لمدينة المثنى وضواحيها" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
cd /tmp/BH-Athan
mplayer duhur.mp3
mplayer adhan11.wma
fi
if [ $time == "17:21:00" ]; then
notify-send "BH-Athan" "حان الان موعد اذان المغرب حسب التوقيت المحلي لمدينة المثنى وضواحيها" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
cd /tmp/BH-Athan
mplayer maghrib.mp3
mplayer adhan11.wma
fi
;;
*)
if [ $time == "05:00:00" ]; then
cd /tmp/BH-Athan
notify-send "BH-Athan" "حان الان موعد اذان الفجر" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
mplayer fajer.mp3
mplayer adhan11.wma
fi
if [ $time == "11:47:00" ]; then
notify-send "BH-Athan" "حان الان موعد اذان الضهر" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
cd /tmp/BH-Athan
mplayer duhur.mp3
mplayer adhan11.wma
fi
if [ $time == "17:21:00" ]; then
notify-send "BH-Athan" "حان الان موعد اذان المغرب" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
cd /tmp/BH-Athan
mplayer maghrib.mp3
mplayer adhan11.wma
fi
;;
esac
done
else
cd /tmp/BH-Athan
if [ ! -f adhan11.wma ]; then
wget http://iraq.iraq.ir/islam/adhan/adhan11.wma
clear
fi
if [ ! -f duhur.mp3 ]; then
wget https://archive.org/download/fajer_201511/duhur.mp3
clear
fi
if [ ! -f fajer.mp3 ]; then
wget https://archive.org/download/fajer_201511/fajer.mp3
clear
fi
if [ ! -f maghrib.mp3 ]; then
wget https://archive.org/download/fajer_201511/maghrib.mp3
clear
fi
while [ 1 ]; do
time=$(date | awk '{print $4}')
con=$(curl -s http://cmyip.com/ | grep "Region:" | awk '{print $3}')
case $con in
Baghdad)
if [ $time == "05:00:00" ]; then
cd /tmp/BH-Athan
notify-send "BH-Athan" "حان الان موعد اذان الفجر حسب التوقيت المحلي لمدينة بغداد وضواحيها." -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
mplayer fajer.mp3
mplayer adhan11.wma
fi
if [ $time == "11:47:00" ]; then
notify-send "BH-Athan" "حان الان موعد اذان الضهر حسب التوقيت المحلي لمدينة بغداد وضواحيها" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
cd /tmp/BH-Athan
mplayer duhur.mp3
mplayer adhan11.wma
fi
if [ $time == "17:21:00" ]; then
notify-send "BH-Athan" "حان الان موعد اذان المغرب حسب التوقيت المحلي لمدينة بغداد وضواحيها" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
cd /tmp/BH-Athan
mplayer maghrib.mp3
mplayer adhan11.wma
fi
;;
Diyala)
if [ $time == "05:00:00" ]; then
cd /tmp/BH-Athan
notify-send "BH-Athan" "حان الان موعد اذان الفجر حسب التوقيت المحلي لمدينة ديالى وضواحيها" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
mplayer fajer.mp3
mplayer adhan11.wma
fi
if [ $time == "11:47:00" ]; then
notify-send "BH-Athan" "حان الان موعد اذان الضهر حسب التوقيت المحلي لمدينة ديالى وضواحيها" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
cd /tmp/BH-Athan
mplayer duhur.mp3
mplayer adhan11.wma
fi
if [ $time == "17:21:00" ]; then
notify-send "BH-Athan" "حان الان موعد اذان المغرب حسب التوقيت المحلي لمدينة ديالى وضواحيها" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
cd /tmp/BH-Athan
mplayer maghrib.mp3
mplayer adhan11.wma
fi
;;
Erbil)
if [ $time == "05:00:00" ]; then
cd /tmp/BH-Athan
notify-send "BH-Athan" "حان الان موعد اذان الفجر حسب التوقيت المحلي لمدينة اربيل وضواحيها" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
mplayer fajer.mp3
mplayer adhan11.wma
fi
if [ $time == "11:47:00" ]; then
notify-send "BH-Athan" "حان الان موعد اذان الضهر حسب التوقيت المحلي لمدينة اربيل وضواحيها" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
cd /tmp/BH-Athan
mplayer duhur.mp3
mplayer adhan11.wma
fi
if [ $time == "17:21:00" ]; then
notify-send "BH-Athan" "حان الان موعد اذان المغرب حسب التوقيت المحلي لمدينة اربيل وضواحيها" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
cd /tmp/BH-Athan
mplayer maghrib.mp3
mplayer adhan11.wma
fi
;;
Basra)
if [ $time == "05:00:00" ]; then
cd /tmp/BH-Athan
notify-send "BH-Athan" "حان الان موعد اذان الفجر حسب التوقيت المحلي لمدينة البصرة وضواحيها" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
mplayer fajer.mp3
mplayer adhan11.wma
fi
if [ $time == "11:47:00" ]; then
notify-send "BH-Athan" "حان الان موعد اذان الضهر حسب التوقيت المحلي لمدينة البصرة وضواحيها" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
cd /tmp/BH-Athan
mplayer duhur.mp3
mplayer adhan11.wma
fi
if [ $time == "17:21:00" ]; then
notify-send "BH-Athan" "حان الان موعد اذان المغرب حسب التوقيت المحلي لمدينة البصرة وضواحيها" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
cd /tmp/BH-Athan
mplayer maghrib.mp3
mplayer adhan11.wma
fi
;;
"Al Anbar")
if [ $time == "05:00:00" ]; then
cd /tmp/BH-Athan
notify-send "BH-Athan" "حان الان موعد اذان الفجر حسب التوقيت المحلي لمدينة الانبار وضواحيها" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
mplayer fajer.mp3
mplayer adhan11.wma
fi
if [ $time == "11:47:00" ]; then
notify-send "BH-Athan" "حان الان موعد اذان الضهر حسب التوقيت المحلي لمدينة الانبار وضواحيها" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
cd /tmp/BH-Athan
mplayer duhur.mp3
mplayer adhan11.wma
fi
if [ $time == "17:21:00" ]; then
notify-send "BH-Athan" "حان الان موعد اذان المغرب حسب التوقيت المحلي لمدينة الانبار وضواحيها" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
cd /tmp/BH-Athan
mplayer maghrib.mp3
mplayer adhan11.wma
fi
;;
Karbala)
if [ $time == "05:00:00" ]; then
cd /tmp/BH-Athan
notify-send "BH-Athan" "حان الان موعد اذان الفجر حسب التوقيت المحلي لمدينة كربلاء المقدسة وضواحيها" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
mplayer fajer.mp3
mplayer adhan11.wma
fi
if [ $time == "11:47:00" ]; then
notify-send "BH-Athan" "حان الان موعد اذان الضهر حسب التوقيت المحلي لمدينة كربلاء المقدسة وضواحيها" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
cd /tmp/BH-Athan
mplayer duhur.mp3
mplayer adhan11.wma
fi
if [ $time == "17:21:00" ]; then
notify-send "BH-Athan" "حان الان موعد اذان المغرب حسب التوقيت المحلي لمدينة كربلاء المقدسة وضواحيها" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
cd /tmp/BH-Athan
mplayer maghrib.mp3
mplayer adhan11.wma
fi
;;
Kirkuk)
if [ $time == "05:00:00" ]; then
cd /tmp/BH-Athan
notify-send "BH-Athan" "حان الان موعد اذان الفجر حسب التوقيت المحلي لمدينة كركوك وضواحيها" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
mplayer fajer.mp3
mplayer adhan11.wma
fi
if [ $time == "11:47:00" ]; then
notify-send "BH-Athan" "حان الان موعد اذان الضهر حسب التوقيت المحلي لمدينة كركوك وضواحيها" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
cd /tmp/BH-Athan
mplayer duhur.mp3
mplayer adhan11.wma
fi
if [ $time == "17:21:00" ]; then
notify-send "BH-Athan" "حان الان موعد اذان المغرب حسب التوقيت المحلي لمدينة كركوك وضواحيها" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
cd /tmp/BH-Athan
mplayer maghrib.mp3
mplayer adhan11.wma
fi
;;
Ninawa)
if [ $time == "05:00:00" ]; then
cd /tmp/BH-Athan
notify-send "BH-Athan" "حان الان موعد اذان الفجر حسب التوقيت المحلي لمدينة نينوى وضواحيها" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
mplayer fajer.mp3
mplayer adhan11.wma
fi
if [ $time == "11:47:00" ]; then
notify-send "BH-Athan" "حان الان موعد اذان الضهر حسب التوقيت المحلي لمدينة نينوى وضواحيها" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
cd /tmp/BH-Athan
mplayer duhur.mp3
mplayer adhan11.wma
fi
if [ $time == "17:21:00" ]; then
notify-send "BH-Athan" "حان الان موعد اذان المغرب حسب التوقيت المحلي لمدينة نينوى وضواحيها" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
cd /tmp/BH-Athan
mplayer maghrib.mp3
mplayer adhan11.wma
fi
;;
Wasit)
if [ $time == "05:00:00" ]; then
cd /tmp/BH-Athan
notify-send "BH-Athan" "حان الان موعد اذان الفجر حسب التوقيت المحلي لمدينة واسط وضواحيها" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
mplayer fajer.mp3
mplayer adhan11.wma
fi
if [ $time == "11:47:00" ]; then
notify-send "BH-Athan" "حان الان موعد اذان الضهر حسب التوقيت المحلي لمدينة واسط وضواحيها" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
cd /tmp/BH-Athan
mplayer duhur.mp3
mplayer adhan11.wma
fi
if [ $time == "17:21:00" ]; then
notify-send "BH-Athan" "حان الان موعد اذان المغرب حسب التوقيت المحلي لمدينة واسط وضواحيها" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
cd /tmp/BH-Athan
mplayer maghrib.mp3
mplayer adhan11.wma
fi
;;
Najaf)
if [ $time == "05:00:00" ]; then
cd /tmp/BH-Athan
notify-send "BH-Athan" "حان الان موعد اذان الفجر حسب التوقيت المحلي لمدينة النجف الاشرف وضواحيها" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
mplayer fajer.mp3
mplayer adhan11.wma
fi
if [ $time == "11:47:00" ]; then
notify-send "BH-Athan" "حان الان موعد اذان الضهر حسب التوقيت المحلي لمدينة النجف الاشرف وضواحيها" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
cd /tmp/BH-Athan
mplayer duhur.mp3
mplayer adhan11.wma
fi
if [ $time == "17:21:00" ]; then
notify-send "BH-Athan" "حان الان موعد اذان المغرب حسب التوقيت المحلي لمدينة النجف الاشرف وضواحيها" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
cd /tmp/BH-Athan
mplayer maghrib.mp3
mplayer adhan11.wma
fi
;;
"Dhi Qar")
if [ $time == "05:00:00" ]; then
cd /tmp/BH-Athan
notify-send "BH-Athan" "حان الان موعد اذان الفجر حسب التوقيت المحلي لمدينة ذي قار وضواحيها" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
mplayer fajer.mp3
mplayer adhan11.wma
fi
if [ $time == "11:47:00" ]; then
notify-send "BH-Athan" "حان الان موعد اذان الضهر حسب التوقيت المحلي لمدينة ذي قار وضواحيها" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
cd /tmp/BH-Athan
mplayer duhur.mp3
mplayer adhan11.wma
fi
if [ $time == "17:21:00" ]; then
notify-send "BH-Athan" "حان الان موعد اذان المغرب حسب التوقيت المحلي لمدينة ذي قار وضواحيها" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
cd /tmp/BH-Athan
mplayer maghrib.mp3
mplayer adhan11.wma
fi
;;
"Al Muthana")
if [ $time == "05:00:00" ]; then
cd /tmp/BH-Athan
notify-send "BH-Athan" "حان الان موعد اذان الفجر حسب التوقيت المحلي لمدينة المثنى وضواحيها" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
mplayer fajer.mp3
mplayer adhan11.wma
fi
if [ $time == "11:47:00" ]; then
notify-send "BH-Athan" "حان الان موعد اذان الضهر حسب التوقيت المحلي لمدينة المثنى وضواحيها" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
cd /tmp/BH-Athan
mplayer duhur.mp3
mplayer adhan11.wma
fi
if [ $time == "17:21:00" ]; then
notify-send "BH-Athan" "حان الان موعد اذان المغرب حسب التوقيت المحلي لمدينة المثنى وضواحيها" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
cd /tmp/BH-Athan
mplayer maghrib.mp3
mplayer adhan11.wma
fi
;;
*)
if [ $time == "05:00:00" ]; then
cd /tmp/BH-Athan
notify-send "BH-Athan" "حان الان موعد اذان الفجر" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
mplayer fajer.mp3
mplayer adhan11.wma
fi
if [ $time == "11:47:00" ]; then
notify-send "BH-Athan" "حان الان موعد اذان الضهر" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
cd /tmp/BH-Athan
mplayer duhur.mp3
mplayer adhan11.wma
fi
if [ $time == "17:21:00" ]; then
notify-send "BH-Athan" "حان الان موعد اذان المغرب" -t 10000 -i "/tmp/BH-Athan/BH-Icon.png"
cd /tmp/BH-Athan
mplayer maghrib.mp3
mplayer adhan11.wma
fi
;;
esac
done
fi
