#!/bin/bash
# This Script Has Been Coded By Black Hawk
GREEN=$(tput setaf a && tput bold)
BLUE=$(tput setaf 6 && tput bold)
RED=$(tput setaf 1 && tput bold)
YEL=$(tput setaf 3 && tput bold)

banner(){
clear
echo $GREEN
echo "       #############################################################"
echo "      ###############################################################"
echo "     ###                Vulnerability Scanner v1.0                 ###"
echo "    ####         This Program Has Been Coded By Black Hawk         ####"
echo "    #### Thanks To : H-k-O-r-E , ErrorX , Mokhalad-Haxor , My Ribs ####"
echo "     ###              Contact Us On Skype : skhacker97             ###"
echo "      ###############################################################"
echo "       #############################################################"
echo $BLUE
}

help(){
clear
echo $GREEN
echo "       #############################################################"
echo "      ###############################################################"
echo "     ###                Vulnerability Scanner v1.0                 ###"
echo "    ####         This Program Has Been Coded By Black Hawk         ####"
echo "    #### Thanks To : H-k-O-r-E , ErrorX , Mokhalad-Haxor , My Ribs ####"
echo "     ###              Contact Us On Skype : skhacker97             ###"
echo "      ###############################################################"
echo "       #############################################################"
echo $BLUE
echo
echo "       Usage : "
echo "                   --url                To Specific The Target"
echo "                   --help               To Get Help ^_^"
echo "                   --update             To Update The Script"
echo
echo  "                  Ex: $0 --url http://example.com"
exit 0
}

banner
if [ "$0" != "/usr/bin/BH-Vuln-Scanner" ]; then
echo "       [-] Dont Change The Name Of My Script -_-"
echo "       [!] To Fix This Problim You Must To Change It To (BH-Vuln-Scanner)"
echo "           ./Rabbit -_-"
echo
exit 0
fi

upb(){
echo $YEL
banner
echo "      [+] Updating Database , Please Wait"
sleep 1.0
clear
banner
echo "      [+] Updating Database , Please Wait."
sleep 1.1
clear
banner
echo "      [+] Updating Database , Please Wait.."
sleep 1.2
clear
banner
echo "      [+] Updating Database , Please Wait..."
}

lod(){
banner
echo "  [+] Scanning"
sleep 1.0
clear
banner
echo "  [+] Scanning."
sleep 1.1
clear
banner
echo "  [+] Scanning.."
sleep 1.2
clear
banner
echo "  [+] Scanning..."
echo
echo
}

update(){
upb
}

if [ "$1" == "--update" ]; then
update
exit 0
fi

if [ "$1" != "--url" ]; then
echo $RED "       [-] Invild Option [$1]"
help
fi

if [ "$2" == "" ]; then
echo $RED "       [-] You Must To Type The Target (URL)!!"
help
fi

if [ ! -f list ]; then
echo $RED "       [-] Missing Files You Must To Update :)"
exit 0
fi
echo $BLUE
lod
while IFS='' read -r line || [[ -n "$line" ]]; do
fl=$(echo $line | awk {'print $1'})
sl=$(echo $line | awk {'print $3'})
tl=$(echo $line | awk {'print $2'})

wget -qO /dev/null $2$fl
CS=$?
if [ $CS == 0 ]; then
echo $RED " [+] Vulnerable With : $sl"
echo $YEL " [!] You Can Exploit It With : $tl"
echo
echo
fi
done < "list.txt"
